"""Back to counter

Revision ID: 0a66dabb885f
Revises: 0bce50ded7fc
Create Date: 2025-03-31 03:03:17.596852

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "0a66dabb885f"
down_revision = "0bce50ded7fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("button", sa.Column("usage_count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("button", "usage_count")
    # ### end Alembic commands ###
