"""Retirement

Revision ID: 0dac126f47d4
Revises: 1f2e695a2f27
Create Date: 2025-03-31 00:13:32.105897

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "0dac126f47d4"
down_revision = "1f2e695a2f27"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
