"""Retirements

Revision ID: 17e7e1b48df1
Revises: ab3bdff911f4
Create Date: 2025-03-31 04:47:52.554406

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "17e7e1b48df1"
down_revision = "ab3bdff911f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
