"""Remove usage_count from public

Revision ID: 260581de42f9
Revises: e4c9207078d6
Create Date: 2025-03-31 01:19:10.853576

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "260581de42f9"
down_revision = "e4c9207078d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("button", "usage_count")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "button",
        sa.Column("usage_count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
