"""Default user

Revision ID: 41bb0413ccef
Revises: 17e7e1b48df1
Create Date: 2025-03-31 05:01:32.568915

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "41bb0413ccef"
down_revision = "17e7e1b48df1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "buttonretirement", sa.Column("created_by", sa.Uuid(), nullable=False)
    )
    op.create_foreign_key(None, "buttonretirement", "user", ["created_by"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "buttonretirement", type_="foreignkey")
    op.drop_column("buttonretirement", "created_by")
    # ### end Alembic commands ###
