"""Include usage_count in ButtonPublic

Revision ID: 8ddbd1acfd6b
Revises: 0a66dabb885f
Create Date: 2025-03-31 03:15:54.021262

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "8ddbd1acfd6b"
down_revision = "0a66dabb885f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
