"""Use default datetime

Revision ID: b321ebb8aa47
Revises: 18dcbde2a683
Create Date: 2025-03-30 05:36:10.535846

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "b321ebb8aa47"
down_revision = "18dcbde2a683"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
