"""Correct cascade

Revision ID: d443da0e1c3e
Revises: 8ddbd1acfd6b
Create Date: 2025-03-31 03:19:39.222591

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "d443da0e1c3e"
down_revision = "8ddbd1acfd6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
