"""Make usage_count hybrid

Revision ID: e4c9207078d6
Revises: 0dac126f47d4
Create Date: 2025-03-31 01:15:40.744041

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "e4c9207078d6"
down_revision = "0dac126f47d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buttonretirement",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("button_id", sa.Uuid(), nullable=False),
        sa.Column("retired_at", sa.DateTime(), nullable=False),
        sa.Column("unretired_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["button_id"],
            ["button.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("buttonretirement")
    # ### end Alembic commands ###
